### ISSUE TITLE
Hide SearchBar / Side of the iconsPanel

### ISSUE THREAD

**Issue by pedrommateus92** [TypeCtrl/ngx-emoji-mart#176]
Hi, 
I'm checking your documentation if is possible to hide the searchbar but I didn't find it.
Do you think is possible to hide it by a new parameter?

My second question is if is possible, like you have in the perLine (horizontally), if is possible to select the number of icons to show "vertically".
Thank you.

**Comment by scttcper** [comment]
there currently isn't a way to do either

**Comment by MateurX** [comment]
But keep it with my comment like a suggestion to be implemented. 👍 
Thank you @scttcper

**Comment by raphaelmichl** [comment]
This issue seems a bit old, but to hide the search bar you could add the following to your global styles.css:
`.hide-emoji-mart-search .emoji-mart-search {
  display: none;
}`

Then use ngClass in your component's html like so:
`<emoji-mart [ngClass]="{'hide-emoji-mart-search' : yourVariable}"></emoji-mart>`

**Comment by scttcper** [comment]
search bar is optional in v2
