### ISSUE TITLE
Sometimes the emoji native is just blank box

### ISSUE THREAD

**Issue by johnfrades** [TypeCtrl/ngx-emoji-mart#225]
Hello, first of all thanks for this wonderful library.
Currently i integrated your library to my app and i manage to make it work, but the problem is, some of the icons it renders on my Input as "Empty Box"

as you can see some of them are empty box, do you have any idea how to fix this?

![image](https://user-images.githubusercontent.com/20201069/60098576-f825ba00-97a9-11e9-89f8-2ba31ebcf828.png)

This is my code
```
  public addEmoji(event) {
        const message = this.inquiryMessageForm.value;
        const emoji = event.emoji.native;
        const wholeMessage = `${message}${emoji}`;
        this.inquiryMessageForm.patchValue(wholeMessage);
    }
```

HTML code

`<emoji-mart set="facebook" [sheetSize]="16" (emojiClick)="addEmoji($event)"></emoji-mart>
`

**Comment by scttcper** [comment]
should no longer be an issue

**Comment by ichepurnoy** [comment]
@johnfrades you were seeing the issue, since you have chosen some non-`native` set. Which is showing up fine  in picker, but not fine in the main page, where _native emojies are being used_ for rendering.
@scttcper  This is still unfortunately an isuee, if emoji set is `Native` , as of current v9.2.0. _But interestingly, the original lib by missive does not have this issue:_ it loads immediately, and auto-hides non-supported emojies.  I guess , it has the solution to this issue, which just shall be ported into your package.
[See this ](https://learn.microsoft.com/en-us/answers/questions/2374614/some-emojis-not-showing-in-browsers-(edge-and-chro?forum=microsoftedge-all&referrer=answers)for ~explanation.  TLDR: this bug happens in Blink-based browsers like Chrome/Edge in Windows 10, and also in some older versions of MacOS (i've seen in Big Sur). Firefox on Win10 does not have the issue.
Check this emoji (should be broken under Win10) [https://emojipedia.org/smiling-face-with-tear#technical](https://emojipedia.org/smiling-face-with-tear#technical). As opposed to others like [https://emojipedia.org/slightly-smiling-face](https://emojipedia.org/slightly-smiling-face)

Solution: i've come up with an ugly fix via `emojisToShowFilter` @ Input, which function is checking against an object of booleans (for each emoji name as key, a boolean value for it to be shown/hidden).  It's ugly 'cause dynamic calculation of it takes a few seconds and a lot of CPU (~1800+ emojies to go over). So, i ended up just hardcoding such object, just for Win10.

<img width="1055" height="601" alt="Image" src="https://github.com/user-attachments/assets/848a383e-d317-4338-87d5-a036e9f1dfc9" />
