### ISSUE TITLE
How it works with contenteditable div?

### ISSUE THREAD

**Issue by Belouccio** [TypeCtrl/ngx-emoji-mart#293]
Can you provide some examples to show how this library works with contenteditable div?
Examples in documentation shows only how to use it separately within textarea or input or div. Thank you.
How get it works to looks like this? 
![image](https://user-images.githubusercontent.com/25301055/73542666-48eb4880-4446-11ea-8f3f-df9db858d1cd.png)

**Comment by s-moran** [comment]
Hi, I have experimented with this a bit. I recommend using the picker only to select the emoji you want, and rendering it in the contenteditable using twemoji (https://github.com/twitter/twemoji)... In other words, the picker can return you the unicode value of the emoji, and then you can render an img element by calling the appropriate method from twemoji API (e.g. twemoji.parse). This is a better approach because <img> tags are  much simpler to handle within a contenteditable as opposed to a complex angular component.

**Comment by scttcper** [comment]
I agree, this gives you the emoji details and a picker, implementing emoji display or text editing is up to the user.

**Comment by Belouccio** [comment]
> Hi, I have experimented with this a bit. I recommend using the picker only to select the emoji you want, and rendering it in the contenteditable using twemoji (https://github.com/twitter/twemoji)... In other words, the picker can return you the unicode value of the emoji, and then you can render an img element by calling the appropriate method from twemoji API (e.g. twemoji.parse). This is a better approach because img tags are much simpler to handle within a contenteditable as opposed to a complex angular component.

Thank you!)
