### ISSUE TITLE
Could not resolve the module's components

### ISSUE THREAD

**Issue by sriharisahu** [TypeCtrl/ngx-emoji-mart#97]
I installed the module and started the server using `ng serve` on angular 5 and got the following on the console:
<pre>
ERROR in @ctrl\ngx-emoji-mart\ctrl-ngx-emoji-mart.ts(25,40): Error during template compile of 'PickerModule'
  Could not resolve @ctrl/ngx-emoji-mart/ngx-emoji relative to C:/workspace/stash/amc/angular/node_modules/@ctrl/ngx-emoji-mart/ctrl-ngx-emoji-mart.d.ts..
node_modules/@ctrl/ngx-emoji-mart/anchors.component.d.ts(2,31): error TS2307: Cannot find module '@ctrl/ngx-emoji-mart/ngx-emoji'.
node_modules/@ctrl/ngx-emoji-mart/emoji-frequently.service.d.ts(1,27): error TS2307: Cannot find module '@ctrl/ngx-emoji-mart/ngx-emoji'.
node_modules/@ctrl/ngx-emoji-mart/category.component.d.ts(2,37): error TS2307: Cannot find module '@ctrl/ngx-emoji-mart/ngx-emoji'.
node_modules/@ctrl/ngx-emoji-mart/emoji-search.service.d.ts(1,41): error TS2307: Cannot find module '@ctrl/ngx-emoji-mart/ngx-emoji'.
node_modules/@ctrl/ngx-emoji-mart/picker.component.d.ts(2,61): error TS2307: Cannot find module '@ctrl/ngx-emoji-mart/ngx-emoji'.
node_modules/@ctrl/ngx-emoji-mart/preview.component.d.ts(2,41): error TS2307: Cannot find module '@ctrl/ngx-emoji-mart/ngx-emoji'.
node_modules/@ctrl/ngx-emoji-mart/skins.component.d.ts(2,23): error TS2307: Cannot find module '@ctrl/ngx-emoji-mart/ngx-emoji'.
</pre>

**Comment by scttcper** [comment]
make sure you're using typescript > 2.6

**Comment by ghndr** [comment]
I'm using typescript 2.5 and I fixed this by going into `node_modules/@ctrl/ngx-emoji-mart` and changing the imports in each file, replacing the `@ctrl/ngx-emoji-mart/` with `./`
for example, I replaced
`import { EmojiData } from  '@ctrl/ngx-emoji-mart/ngx-emoji'`
with
`import { EmojiData } from './ngx-emoji';`

of course, if you follow this approach you will have to repeat this process whenever you update the package, so it would be better to simply update typescript, otherwise, this solution should work.
